### ISSUE TITLE
Support for Valkyries/Warrior Stacks on boss bar or character hp bar similar to how it works currently.

### ISSUE THREAD

**Issue by hunter1128** [Foglio1024/Tera-custom-cooldowns#35]
So I have been trying to use this and removing or disabling innate ingame ui but its kind of impossible to do on these two classes atm since there is no way for me to see the stacks. besides all of this gj keep up the good work.

Thanks

**Comment by Foglio1024** [comment]
I'm planning to add stack support but not under boss bar. It will be a separate bar with fixed skill icons and other info specific to the class you're playing at the moment. For example it will show warrior/valkyrie stacks, duration and cooldown of self buffs like Deadly Gamble, Guardian Shout, Shadow Reaping, Mana Boost, etc. I may include hp and mp bar too, so that this bar will replace cooldown + character windows.

**Comment by Foglio1024** [comment]
Stacks added to class specific bar
